In [2]:
import numpy as pro

In [3]:
fromlist1= pro.array([22,40,30,60,70])
fromlist2= pro.array((1,3,2,5,6,7))
print(fromlist1)
print(type(fromlist1))
print(fromlist2)

[22 40 30 60 70]
<class 'numpy.ndarray'>
[1 3 2 5 6 7]


In [6]:
lay2d = pro.array([[2,3,6,7],[7,6,4,3]])
print(lay2d)

[[2 3 6 7]
 [7 6 4 3]]


In [32]:
nos1=[1,2,3,4,5,6,7]
nos2=[10,20,25,30,40,50,55]
sum_list=map(lambda x,y:x+y,nos1,nos2)
# sum_list(10,10)
print(list(sum_list))

[11, 22, 28, 34, 45, 56, 62]


In [33]:
array1=pro.array(nos1)
array2= pro.array(nos2)
sum_array= array1+array2
print(sum_array)

[11 22 28 34 45 56 62]


In [26]:
xs = [1, 2, 3]
yy=[*map(lambda x:x*2,xs)]
print(yy)

[2, 4, 6]


In [41]:
datatype= pro.array([1,2,4,5,6,7],dtype=float)
datatype1= pro.array([1.02,2,4,5,6,7],dtype=float)
print(type(datatype))
print(datatype)
print(datatype1)

<class 'numpy.ndarray'>
[1. 2. 4. 5. 6. 7.]
[1.02 2.   4.   5.   6.   7.  ]


In [44]:
state= datatype >= 3
print(state)

[False False  True  True  True  True]


In [48]:
datatype[state]

array([4., 5., 6., 7.])

In [47]:
d2= pro.array([[1,2,3,4],[3,6,9,12]])
d2

array([[ 1,  2,  3,  4],
       [ 3,  6,  9, 12]])

# Initialize array

In [7]:
# help(pro.array)
incr= pro.arange(1,15,3)
print(incr)
decr= pro.arange(25,5,-2)
print(decr)
dd=pro.resize(decr,(5,3))
print(dd)

[ 1  4  7 10 13]
[25 23 21 19 17 15 13 11  9  7]
[[25 23 21]
 [19 17 15]
 [13 11  9]
 [ 7 25 23]
 [21 19 17]]


In [83]:
pro.zeros(((3,2)),dtype = int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [76]:
pro.ones(4)

array([1., 1., 1., 1.])

In [84]:
pro.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [92]:
pro.random.random((4,2))

array([[0.59687394, 0.0081746 ],
       [0.8447773 , 0.61146232],
       [0.99444259, 0.51338681],
       [0.54851561, 0.48835907]])

In [112]:
pro.random.randint(1,10,(3,4))

array([[8, 8, 1, 5],
       [9, 7, 5, 5],
       [9, 3, 8, 3]])

In [127]:
pro.full(3,5)

array([5, 5, 5])

In [97]:
pro.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [130]:
# identity matrix
i_matr= pro.eye(5, dtype=int)
# i_matr= pro.eye(5,3, dtype=int)
i_matr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [116]:
pro.linspace(1,10,6)
# equal increment

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [125]:
array4=([1,4,7])
pro.tile(array4,(2,3))

array([[1, 4, 7, 1, 4, 7, 1, 4, 7],
       [1, 4, 7, 1, 4, 7, 1, 4, 7]])

In [16]:
sample=pro.arange(2,20,2).reshape(3,3)
sample

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [28]:
sample1=pro.arange(0,15)
print(pro.resize(sample1,(4,3)))
# print(pro.reshape(sample1,(3,3))) can also work like dis shape is always fixed

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [31]:
cc=pro.reshape(sample1,(5,-1))
cc

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [32]:
cc.T
# T to transpose matrix

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [33]:
yy=pro.append(sample1,[5,6])
yy

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18,  5,  6])

In [36]:
zz=pro.insert(sample1, 4,22)
zz

array([ 0,  1,  2,  3, 22,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
zz=pro.delete(sample1,[7])
# or [4,5]
zz

array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 14])

In [47]:
aray1= pro.arange(0,9).reshape(3,3)
aray2= pro.arange(0,12).reshape(3,4)
print(aray1)
print(aray2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [66]:
aray3= pro.arange(9,18).reshape(3,3)
print(pro.concatenate((aray1,aray3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [51]:
aray1+aray3

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [53]:
pro.hstack((aray1,aray2))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11]])

In [55]:
pro.vstack((aray1,aray3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [61]:
pro.r_[aray1,aray3]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [65]:
pro.c_[aray1,aray3]

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

   # Vectorize

In [69]:
aray6=([10,11,13,14,15,17,20,23])
aray7= pro.array(aray6)
aray7

array([10, 11, 13, 14, 15, 17, 20, 23])

In [75]:
vect= pro.vectorize(lambda x: x*3+x**2)
vect(aray7)

array([130, 154, 208, 238, 270, 340, 460, 598])

In [76]:
vect(aray3)

array([[108, 130, 154],
       [180, 208, 238],
       [270, 304, 340]])